### ISSUE TITLE
Steam connected but not importing any titles (library too big?)

### ISSUE THREAD

**Issue by McKack** [FriendsOfGalaxy/galaxy-integration-steam#7]
![Annotation 2019-08-16 143106](https://user-images.githubusercontent.com/4465550/63167831-b6d7bb00-c032-11e9-821f-a4d2e90e0e6f.png)

Steam seems to be connected and I get friend suggestions from Steam but I see no Steam icon on the Recent page and never get a progress bar or any indication that titles are being imported and if I leave Galaxy open it just fills the log with thousands(!) of these **"result":null** lines and a few of the **"message":"Backend error"** ones
`2019-08-16 14:33:12,960 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "6", "error": {"code": 4, "message": "Backend error"}}
2019-08-16 14:33:15,256 - root - DEBUG - Received 54 bytes of data
2019-08-16 14:33:15,256 - root - INFO - Handling request: id=9, method=ping, params={}
2019-08-16 14:33:15,256 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "9", "result": null}
2019-08-16 14:33:20,279 - root - DEBUG - Received 55 bytes of data
2019-08-16 14:33:20,279 - root - INFO - Handling request: id=10, method=ping, params={}
2019-08-16 14:33:20,279 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "10", "result": null}
2019-08-16 14:33:25,318 - root - DEBUG - Received 55 bytes of data
2019-08-16 14:33:25,318 - root - INFO - Handling request: id=11, method=ping, params={}
2019-08-16 14:33:25,318 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "11", "result": null}`

- I have over [10k titles in my library](https://steamcommunity.com/id/mckack/games/?tab=all) (page will most likely freeze if you try to load it), is this maybe related?
- Other integrations work as expected.

**Comment by Danyelalejandro** [comment]
I have almost 2000 titles and I had experienced different issues:
1. The plugin crashed a lot on last update
2. The lack of covers is tremendous. Almost 500 titles did not have any cover. I had to add them manually one by one, and right now, they have dissapeard. So I lost all that time. 
3. The number of titles os not the same as they appear in my steam Library, It is a lot of missing games but I do not have the time to check one by one.

Some of the developers has been able to extract data from Steamdb? Covers maybe? Info about titles? Something is wrong about our steam data, or else we will be able to see all our games with all covers.

The ones we have big libraries with unknown or "shovelware" games are doomed? Thankfully this is a beta, hoping they will hear us. Thanks on advance

**Comment by Elikay** [comment]
>     1. The plugin crashed a lot on last update

I believe this has been fixed with the recent update, as long as you can get through the initial start up of the plugin, before it would continuously search for games regardless if the library updated or not. The initial startup is still quite intensive though and may crash on weaker machines with larger libraries.

>     2. The lack of covers is tremendous. Almost 500 titles did not have any cover. I had to add them manually one by one, and right now, they have dissapeard. So I lost all that time.
>     3. The number of titles is not the same as they appear in my steam Library, It is a lot of missing games but I do not have the time to check one by one.
>
> Some of the developers has been able to extract data from Steamdb? Covers maybe? Info about titles? Something is wrong about our steam data, or else we will be able to see all our games with all covers.

I believe this is an issue with how Galaxy is currently handling game information. I don't know entirely how it's handled, but I believe they use their own database, rather than importing information from others. As for why the custom game covers disappeared, I also don't know, and that's very unfortunate. I recall hearing there is also a custom artwork limit in the client right now, I'd recommend holding off from manually doing large manual conversions like that until after the client has entered open beta. At the moment most of these scenarios are limitations of the Galaxy client and Galaxy API, that will hopefully be fleshed out by the time we reach a full release. 

I also believe with the current methods being used, there are many things not imported either because they can't be found, or aren't considered games. I for example have several pieces of software in my steam library that's not imported. I also have several beta copies and prototype games in my library that also don't get imported. I believe this may be related to the number discrepancy between the number shown in steam and the number shown in GOG.

> The ones we have big libraries with unknown or "shovelware" games are doomed? Thankfully this is a beta, hoping they will hear us. Thanks on advance

At the moment perhaps, but it's games like those that GOG is known for. I'm not too worried about it yet, but it's too early to tell. I believe they'll be creating some sort of way for the community to add these games manually themselves, allowing the community to import information from other databases, to make GOG's own database stronger. 

If either of you could pin point any exact examples, I may be able to take a deeper look just to ensure that there's not also a bug in play here too.

**Comment by Danyelalejandro** [comment]
Thank you @Elikay, I can confirm to you:
1. Crashes still happens, even with last update
2. I added again all missing covers and it has not been erased again
3. Not all games are shown. By example: My Sherlock Holmes collection does not appear complete in GOGalaxy 2.0 but it does on Steam launcher.

I will attach my log. I hope this can help to improve the plugin and provide a better experience to users with libraries as big as mine.

Thank you so much!!!
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3844077/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
@Danyelalejandro There is few problems from what i see in your log file:

1. parse error in 3rd party module. You should create an issue here: https://github.com/ValvePython/vdf/issues pasting folowing part of your log and uploading the acf file
```
2019-11-13 18:23:25,730 - root - ERROR - Failed to parse e:/steam\steamapps\appmanifest_322330.acf
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 121, in parse
    line += next(fp)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 211, in get_app_id
    config = load_vdf(app_manifest_path)
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 21, in load_vdf
    return vdf.load(open(path, encoding="utf-8", errors="replace"), mapper=CaseInsensitiveDict)
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 186, in load
    return parse(fp, **kwargs)
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\vdf\__init__.py", line 124, in parse
    raise SyntaxError("vdf.parse: unexpected EOF (open key quote?)")
  File "<string>", line None
SyntaxError: vdf.parse: unexpected EOF (open key quote?)
```

2.
```
2019-11-13 18:23:26,733 - root - ERROR - Failed to parse e:/steam\steamapps\appmanifest_416680.acf
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 212, in get_app_id
    return config["AppState"]["appid"]
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 17, in __getitem__
    return super().__getitem__(key.lower())
KeyError: 'appstate'
```

this apparently is on our side. Could you send us this file? `e:/steam\steamapps\appmanifest_416680.acf` or `e:/steam\steamapps\appmanifest_247080.acf` ?

3. Those error appears every second. Looks like regresion with #10 despite #11 . That is not good. I'll check one more time.

4. there is nothing in log file that shows your plugin total crash. I will appreciate i you send log file _just after_ the crash. This way proper information won't be misssed.

> I added again all missing covers and it has not been erased again

That's nice that Galaxy fixed it.

> Not all games are shown. By example: My Sherlock Holmes collection does not appear complete in GOGalaxy 2.0 but it does on Steam launcher.

This is Galaxy gamesdb problem. I see 3 games that are send from plugin to Galaxy that contains "Sherlock" in title. How many do you have in Steam? Note, that DLCs are not handled by plugin/Galaxy yet.

If you Galaxy is missing a game and its title appears in plugin log (under "owned_games"), then this game is probably spammed by their filters, and should be fixed within a few weeks if you send a bug report via the client cogwheel menu.

**Comment by FriendsOfGalaxy** [comment]
@McKack 
result: null is ok. Galaxy is pinging plugin if it sill alive, plugin responds with null. BackendError is not. Maybe Steam limits your connection when getting achievements or titles?

Can you:
- close Galaxy,
- delete your steam logs (also those with numbers)
- Connect Galaxy (and steam plugin if not connected already)
- zip and upload fresh all log files here?

**Comment by McKack** [comment]
Here's the fresh Steam logs after running Galaxy for around 5 minutes.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854356/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.zip)

**Comment by Danyelalejandro** [comment]
> @Danyelalejandro There is few problems from what i see in your log file:
> 
> 1. and 2. : let us move to separated issue: #16
> 2. Those error appears every second. Looks like regresion with #10 despite #11 . That is not good. I'll check one more time.
> 3. there is nothing in log file that shows your plugin total crash. I will appreciate i you send log file _just after_ the crash. This way proper information won't be misssed.
> 
> > I added again all missing covers and it has not been erased again
> 
> That's nice that Galaxy fixed it.
> 
> > Not all games are shown. By example: My Sherlock Holmes collection does not appear complete in GOGalaxy 2.0 but it does on Steam launcher.
> 
> This is Galaxy gamesdb problem. I see 3 games that are send from plugin to Galaxy that contains "Sherlock" in title. How many do you have in Steam? Note, that DLCs are not handled by plugin/Galaxy yet.
> 
> If you Galaxy is missing a game and its title appears in plugin log (under "owned_games"), then this game is probably spammed by their filters, and should be fixed within a few weeks if you send a bug report via the client cogwheel menu.

I have moved to separate issue.
I have 6 Sherlock Holmes games in my steam library but client only shows 3
![image](https://user-images.githubusercontent.com/53067616/68998615-d45f2f80-0882-11ea-9887-83bbb3b8c7f2.png)
I have 2699 games in my Steam Library and 467610 achievements

**Comment by Danyelalejandro** [comment]
All ACF zipped
[appmanifest_.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3854638/appmanifest_.zip)

**Comment by Danyelalejandro** [comment]
@FriendsOfGalaxy
Reported issue of " parse error in 3rd party module #23" was closed. They answered this:
I see. There are two errors I see.

Failed to parse e:/steam\steamapps\appmanifest_322330.acf looking at the file you've sent, its empty. Well not exactly, its 766 bytes and filled with nulls (0x00). So the input is invalid.

2019-11-13 18:23:26,733 - root - ERROR - Failed to parse e:/steam\steamapps\appmanifest_416680.acf
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 212, in get_app_id
    return config["AppState"]["appid"]
  File "C:\Users\usuario\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\client.py", line 17, in __getitem__
    return super().__getitem__(key.lower())
KeyError: 'appstate'
This is error comes from other code thats not the vdf package.

**Comment by FriendsOfGalaxy** [comment]
@McKack you're probably right: the error comes from parsing your games profile: https://steamcommunity.com/id/mckack/games/?tab=all
I'm currently working on alternative solution for getting owned games in more efficient way.

@Danyelalejandro do you find all of your Sherlock Holmes games in in steam web profile when you log in?

**Comment by Danyelalejandro** [comment]
Hello @FriendsOfGalaxy 
Yes, they do appear in my library:
![image](https://user-images.githubusercontent.com/53067616/69200322-c4588180-0b08-11ea-99ba-7ef1e800bb7b.png)
But in GOG galaxy 2.0:
![image](https://user-images.githubusercontent.com/53067616/69201173-66796900-0b0b-11ea-9f34-c47d143578cf.png)

Interestingly, these games are not unknown by GOG, they even are in their store.

I will attach my new logs if they are of any help.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3866887/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by FriendsOfGalaxy** [comment]
@Danyelalejandro let us move your issue to #18

**Comment by FriendsOfGalaxy** [comment]
@McKack I've checked web profiles of people that have more games than you and it works. Maybe you should write to steam support about this?

**Comment by FriendsOfGalaxy** [comment]
we dont use web profile scanning anymore
